stages:
  - linting
  - test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/style.txt
    - flake8 .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black  --diff --color .

test:
  stage: test
  image: python:3.12
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: postgres
    POSTGRES_NAME: postgres
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    DATABASE_URL: "postgres://admin:admin@postgres:5432/postgres"
  script:
    - pip install -r requirements/test.txt
    - cd yat
    - python manage.py test