# Generated by Django 5.0 on 2024-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="activation_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
