# Generated by Django 5.0 on 2024-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_event_scores_alter_task_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                related_name="notes", to="homepage.tag"
            ),
        ),
    ]
