# Generated by Django 5.0 on 2024-04-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_score_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
