# Generated by Django 5.0 on 2024-04-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_task_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="factors",
        ),
        migrations.AddField(
            model_name="task",
            name="scores",
            field=models.ManyToManyField(
                related_name="tasks", to="homepage.score"
            ),
        ),
    ]
