# Generated by Django 5.0 on 2024-04-18 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_remove_task_factors_task_scores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("done", "Выполнена"), ("not done", "Не выполнена")],
                default="not done",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now=True)),
                ("finished", models.DateTimeField()),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="homepage.activity",
                    ),
                ),
                (
                    "scores",
                    models.ManyToManyField(
                        related_name="events", to="homepage.score"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="events", to="homepage.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
