# Generated by Django 5.0 on 2024-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_alter_task_status_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
