# Generated by Django 5.0 on 2024-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_alter_event_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
