# Generated by Django 5.0 on 2024-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_alter_event_created_alter_task_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="done",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
