# Generated by Django 5.0 on 2024-04-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0011_task_done_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scores",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="homepage.score"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="scores",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="homepage.score"
            ),
        ),
    ]
